# EXPERIMENT - WEEK 3

#### Importing packages

In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

#### Loading cleaned dataset from week 3 experiment

In [6]:
train_df = pd.read_csv('../data/interim/cleaned_train_data_draft_pred.csv')
test_df = pd.read_csv('../data/interim/cleaned_test_data_draft_pred.csv')

In [7]:
train_df.head(5)

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id,drafted
0,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,4.6,...,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,7be2aead-da4e-4d13-a74b-4c1e692e2368,0.0
1,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,6.3,...,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,61de55d9-1582-4ea4-b593-44f6aa6524a6,0.0
2,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,8.0,...,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,efdc4cfc-9dd0-4bf8-acef-7273e4d5b655,0.0
3,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,9.4,...,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,14f05660-bb3c-4868-b3dd-09bcdb64279d,0.0
4,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,18.6,...,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,a58db52f-fbba-4e7b-83d0-371efcfed039,0.0

In [8]:
test_df.head(5)

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,...,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id
0,Morgan St.,MEAC,2,3.0,115.1,4.7,50.0,50.00,0.0,4.6,...,-2.467740,-2.275660,0.0000,0.3333,0.3333,0.0000,0.0000,0.0000,1.0000,cf302b4d-84f7-4124-a25d-a75eed31978b
1,South Carolina St.,MEAC,11,17.6,61.1,18.6,34.7,35.18,2.5,15.7,...,-7.494720,-4.412530,0.2727,1.4545,1.7273,0.4545,0.1818,0.0000,2.3636,f91837cd-4f49-4b70-963d-aeb82c6ce3da
2,Binghamton,AE,9,28.6,91.9,23.8,54.1,52.49,6.4,22.5,...,-2.924950,1.717890,1.3333,4.4444,5.7778,1.0000,0.6667,1.8889,8.8889,53ec2a29-1e7d-4c6d-86d7-d60d02af8916
3,Illinois,B10,7,1.3,111.0,10.4,83.3,83.33,0.0,13.4,...,-0.767911,0.962469,0.0000,0.2857,0.2857,0.0000,0.0000,0.0000,0.7143,32402798-471c-4a54-8cb4-29cd95199014
4,Iowa St.,B12,23,78.5,103.1,21.5,54.0,56.12,3.6,10.2,...,2.893610,-1.019000,1.0435,2.8696,3.9130,1.1739,0.8261,0.0870,14.3043,73b960f9-27b8-4431-9d23-a760e9bbc360

In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
from src.data.encoders import perform_one_hot_encoding

In [28]:
to_encode = ['conf', 'yr']
train_df_one_enc, test_df_one_enc = perform_one_hot_encoding(train_df, test_df, to_encode)

In [33]:
train_df_one_enc.head(5)

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,conf_SEC,conf_SLND,conf_SUM,conf_SWAC,conf_WAC,conf_WCC,yr_Fr,yr_Jr,yr_So,yr_Sr
0,26,29.5,97.3,16.6,42.5,44.43,1.6,4.6,15.8,16.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,34,60.9,108.3,14.9,52.4,54.48,3.8,6.3,13.6,19.8,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,27,72.0,96.2,21.8,45.7,47.98,2.1,8.0,14.7,15.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,30,44.5,97.7,16.0,53.6,53.69,4.1,9.4,13.7,23.8,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,33,56.2,96.5,22.0,52.8,54.31,8.3,18.6,8.2,22.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

##### NOTE: Removing team from the feature set as new values are seen in the test data. To be dealt in next experiment

In [30]:
train_df_one_enc = train_df_one_enc.drop('team', axis=1)
test_df_one_enc = test_df_one_enc.drop('team', axis=1)

In [37]:
train_df_one_enc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56091 entries, 0 to 56090
Data columns (total 99 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GP                   56091 non-null  int64
 1   Min_per              56091 non-null  float64
 2   Ortg                 56091 non-null  float64
 3   usg                  56091 non-null  float64
 4   eFG                  56091 non-null  float64
 5   TS_per               56091 non-null  float64
 6   ORB_per              56091 non-null  float64
 7   DRB_per              56091 non-null  float64
 8   AST_per              56091 non-null  float64
 9   TO_per               56091 non-null  float64
 10  FTM                  56091 non-null  int64
 11  FTA                  56091 non-null  int64
 12  FT_per               56091 non-null  float64
 13  twoPM                56091 non-null  int64
 14  twoPA                56091 non-null  int64
 15  twoP_per             56091 non-null  float64
 16  TPM                  56091 non-null  int64
 17  TPA                  56091 non-null  int64
 18  TP_per               56091 non-null  float64
 19  blk_per              56091 non-null  float64
 20  stl_per              56091 non-null  float64
 21  ftr                  56091 non-null  float64
 22  ht                   55728 non-null  float64
 23  num                  56091 non-null  float64
 24  porpag               56091 non-null  float64
 25  adjoe                56091 non-null  float64
 26  pfr                  56091 non-null  float64
 27  year                 56091 non-null  int64
 28  Rec_Rank             17036 non-null  float64
 29  ast_tov              51901 non-null  float64
 30  rimmade              50010 non-null  float64
 31  rimmade_rimmiss      50010 non-null  float64
 32  midmade              50010 non-null  float64
 33  midmade_midmiss      50010 non-null  float64
 34  rim_ratio            46627 non-null  float64
 35  mid_ratio            46403 non-null  float64
 36  dunksmade            50010 non-null  float64
 37  dunksmiss_dunksmade  50010 non-null  float64
 38  dunks_ratio          25298 non-null  float64
 39  pick                 1386 non-null   float64
 40  drtg                 56047 non-null  float64
 41  adrtg                56047 non-null  float64
 42  dporpag              56047 non-null  float64
 43  stops                56047 non-null  float64
 44  bpm                  56047 non-null  float64
 45  obpm                 56047 non-null  float64
 46  dbpm                 56047 non-null  float64
 47  gbpm                 56047 non-null  float64
 48  mp                   56053 non-null  float64
 49  ogbpm                56047 non-null  float64
 50  dgbpm                56047 non-null  float64
 51  oreb                 56053 non-null  float64
 52  dreb                 56053 non-null  float64
 53  treb                 56053 non-null  float64
 54  ast                  56053 non-null  float64
 55  stl                  56053 non-null  float64
 56  blk                  56053 non-null  float64
 57  pts                  56053 non-null  float64
 58  player_id            56091 non-null  object
 59  drafted              56091 non-null  float64
 60  conf_A10             56091 non-null  float64
 61  conf_ACC             56091 non-null  float64
 62  conf_AE              56091 non-null  float64
 63  conf_AMER            56091 non-null  float64
 64  conf_ASUN            56091 non-null  float64
 65  conf_B10             56091 non-null  float64
 66  conf_B12             56091 non-null  float64
 67  conf_BE              56091 non-null  float64
 68  conf_BSKY            56091 non-null  float64
 69  conf_BSTH            56091 non-null  float64
 70  conf_BW              56091 non-null  float64
 71  conf_CAA             56091 non-null  float64
 72  conf_CUSA            56091 non-null  float64
 73  conf_GWC             56091 non-null  float64
 74  conf_HORZ            56091 non-null  float64
 75  conf_IND             56091 non-null  float64
 76  conf_IVY             56091 non-null  float64
 77  conf_MAAC            56091 non-null  float64
 78  conf_MAC             56091 non-null  float64
 79  conf_MEAC            56091 non-null  float64
 80  conf_MVC             56091 non-null  float64
 81  conf_MWC             56091 non-null  float64
 82  conf_NEC             56091 non-null  float64
 83  conf_OVC             56091 non-null  float64
 84  conf_P10             56091 non-null  float64
 85  conf_P12             56091 non-null  float64
 86  conf_PAT             56091 non-null  float64
 87  conf_SB              56091 non-null  float64
 88  conf_SC              56091 non-null  float64
 89  conf_SEC             56091 non-null  float64
 90  conf_SLND            56091 non-null  float64
 91  conf_SUM             56091 non-null  float64
 92  conf_SWAC            56091 non-null  float64
 93  conf_WAC             56091 non-null  float64
 94  conf_WCC             56091 non-null  float64
 95  yr_Fr                56091 non-null  float64
 96  yr_Jr                56091 non-null  float64
 97  yr_So                56091 non-null  float64
 98  yr_Sr                56091 non-null  float64
dtypes: float64(90), int64(8), object(1)
memory usage: 42.4+ MB

In [ ]:
def feature_selection_statistical_test():